#!/bin/sh

set -e

echo "Running Deno lint..."
deno task lint

echo "Running Deno check..."
deno task check

echo "Running Deno fmt..."
deno task fmt

echo "Checking Deno formatting..."
deno fmt --check

echo "Running Deno tests..."
deno task test

echo "All checks passed. Proceeding with push."
